name: Build and Push Docker Image

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build Docker image
      run: docker build -t bdcanop/top_soft_taller2img1:latest -f Dockerfile .

    
    - name: Push Docker image
      run: docker push bdcanop/top_soft_taller2img1:latest
